/*PARTIE 2 : MODIFICATION DE DONNEES*/
/*Question 1*/
UPDATE Segment SET etage=0 WHERE indIP = '130.120.80';
UPDATE Segment SET etage=1 WHERE indIP = '130.120.81';
UPDATE Segment SET etage=2 WHERE indIP = '130.120.82';
SELECT * FROM Segment;

/*Question 2 Dimunier le prix de 10% des logiciels T001*/
UPDATE LOGICIEL SET PRIX=0.9*PRIX WHERE TYPELP="T001";

/*PARTIE 3 : MODIFICATION DE LA STRUCTURE DES TABLES*/
/*Question 1*/
ALTER TABLE SEGMENT 
ADD COLUMN nbSalle SMALLINT DEFAULT 0,/*TOUJOURS PRECISER COLUMN SI INSERTION MULTIPLE DE COLONNES*/
ADD COLUMN nbPoste SMALLINT DEFAULT 0;

ALTER TABLE LOGICIEL ADD COLUMN nbInstall SMALLINT DEFAULT 0;

ALTER TABLE POSTE ADD COLUMN nbLog SMALLINT DEFAULT 0;

/*Question 2*/
ALTER TABLE SALLE MODIFY COLUMN NOMSALLE VARCHAR(30);

/*Question 3*/
ALTER TABLE SEGMENT MODIFY COLUMN NOMSEGMENT VARCHAR(15);

/*Question 4*/
ALTER TABLE SEGMENT MODIFY COLUMN NOMSEGMENT VARCHAR(12);/*=> IMPOSSIBLE CAR PERTE DE DONNEES
 ET LES DONNEES DEJA RENSEIGNER ONT UNE TAILLE <=13 */

/*Question 5*/
ALTER TABLE INSTALLER
ADD CONSTRAINT UC_Installation UNIQUE (NPOSTE, NLOG);

